[theme]
base="dark"
primaryColor="#FFFFFF"
backgroundColor="#12418C"
secondaryBackgroundColor="#0f376f"
textColor="#FFFFFF"
font="sans serif"

[global]
disableWatchdogWarning = true

[server]
headless = true
enableCORS = false
port = 8501
